### ISSUE TITLE
a bug in handling GETX request in LLC?

### ISSUE THREAD

**Issue by gskim12** [s5z/zsim#168] opened 2017-07-11 21:30 UTC
Hi,
It seems like there is a bug that results in incorrect latency for handling GETX request in LLC if the cache line is currently in S state. In line 120-130 in coherence_ctrls.cpp, assuming this was LLC, the parent is memory controller. If the line is currently in S state, the LLC already has the cache line data, so it doesn't need to access DRAM, but it calls parents[]->access() anyway, and that adds DRAM access latency. 
Am I missing something?
Thanks.

**Comment by gaomy3832** [comment] 2017-07-11 21:42
Because zsim enforces a single LLC, a read-only data copy will always be in E state in LLC, and should never turn to S state (theoretically, I haven't confirmed this). So GETX to LLC should always silently upgrade, i.e., hit the other branch below the code you pointed to.

Have you seen any violation in real simulation runs? That should confirm if my guess is correct or not.

**Comment by gskim12** [comment] 2017-07-11 22:25
Ok. Now I understand. I haven't seen any violation. 
Thanks for the response.

**Comment by gaomy3832** [comment] 2017-07-13 02:20
Please close this issue if your question has been resolved.

**Closed as completed** 2017-07-13 02:21 UTC
